### ISSUE TITLE
Tibber API clients must implement graphql-transport-ws sub-protocol

### ISSUE THREAD

**Issue by ztamas83** [Danielhiversen/PyGraphqlWebsocketManager#31]
The latest addition on the Tibber API docs (https://developer.tibber.com/docs/guides/calling-api) clearly states some requirements on the GraphQL subscriptions and the current implementation in PyGraphqlWebsocketManager will not be supported from December 2022.

I would like to contribute by implementing the support for the [graphql-transport-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) sub-protocol if work is not already being done by you @Danielhiversen or @toini.

**Comment by Danielhiversen** [comment]
It was implemented some months ago
https://github.com/Danielhiversen/PyGraphqlWebsocketManager/pull/24

**Comment by ztamas83** [comment]
my bad...

**Comment by toini** [comment]
The thing we need to be careful about is to switch to the new dynamic websocket server address. The caller will need to take care of that.

**Comment by toini** [comment]
@ztamas83 if you are not using pyTibber you can see here how the websocket server url could be fetched: https://github.com/Danielhiversen/pyTibber/pull/213

**Comment by ztamas83** [comment]
> @ztamas83 if you are not using pyTibber you can see here how the websocket server url could be fetched: [Danielhiversen/pyTibber#213](https://github.com/Danielhiversen/pyTibber/pull/213)

Thank you! I do use pyTibber implicitly, I was trying to help fix the HA integration but I trust you guys are working on it as much as you can. Let me know if I can help with anything, I'm happy to code.

 > The thing we need to be careful about is to switch to the new dynamic websocket server address. The caller will need to take care of that.
This is tricky, there is no way to know if the caller did the dynamic resolution of the websocket address or not, but that is actually a Tibber requirement and not something that a generic subscription manager need to bother about.

I assume the dynamic resolution is for load balancing, so if a few users hardcode the addresses and the majority still use the compatible libraries the effect will be not that big.

**Comment by toini** [comment]
The load balancing actually happens under the hood. The reason for dynamically fetching the websocket url was about controlling the migration to the new service (one dedicated to websockets) and avoiding people needing to hard code yet another url in their code. Also, having full control of the url might be useful e.g. for troubleshooting in the future.

In the future api.tibber.com will not support websockets at all. We want to shut it down as there are many clients behaving badly connecting to it. Some of them seem to be just left there effectively DDOSing us and we are not expecting all of them to get updated to the new sub protocol not leaking memory.
